#!/usr/bin/awk -f
#
# Convert genePred file to a bed file (on stdout) #
BEGIN {
FS="[\t;]";
#OFS="\t";
OFS=" "; 
startid=""; }
{
seqid=$1
source=$2 
type=$3 
start=$4-1 
end=$5 
score=$6 
strand=$7 
phase=$8
ID=$9
delete count
split($10, count, "=");
nf_list=$11
f_list=$12
if (seqid!=startid) {
print "variableStep", "chrom="seqid, "span=50"
startid=seqid
}
for (i = start; i <= end; i=i+50) {
print i, count[2];}

}

